language: ruby
rvm:
- ruby-head
deploy:
  provider: heroku
  app: sleepy-eyrie-59687
  api_key:
    secure: oxFQDXmqz8L2gi6uk5KyRQ5eh9IM5owgvJElKMNAsv1hXOjJ7fy/TmeCJttovGo6rlZCZwtB620GiHQZrBoNWZyfkWrcds3XqUmKByZ8irWVX8RMrtUiUtJSPsYx4ZcekPn2JnmsE/hxJOWZYDMrgRFTNUiWgqCwZeKdVtcVB3TJwMzWTGxSH9CSQ14qOxk+ZG50ywhRKgMEhZ/NG7EvjaCKmTYs+ZCUTAUxrII2iY0cGy9OcVyojYNhd6aCyhhXmWabZ0pQKWvYy4CL4bt+G7wbD/6OknOx/RY4HiysWiTQdSeEtuDMc9hKEHpp0QNyZh8HPljXeKOqa6Fdowj/vidKVL8DzKUunpWPBkDSu16qZXAdpuD1zXwD9cXDPPPeIOvruYZqHThc6LoYmZmgoTtELEacBNNaz1z4kMKq81yTZKguPKkbDZ12uZJGGC7h1RJ5tlpXmIJdK2lVgKRr37F9mYFrKvmB7dg7b0oCEXycoFgpX6UlAvgDIH9jr2CyeATsGsM0EjbsShhA8xANHwIJgNX0nsKdfOyyk66q04L2C+6AuO6btJgE9oZnMO+4Ov0it68N4w99v9wuU7jYZv378mfUwINm70bHFoXMwXF3cEQEputUbJDYAQZYUDxwJagQ1EfHNeqKr0ypTq1HOh9Cofv9JPtoGDbMu4lgpZE=
